### PR TITLE
Added debug icon, app name, and version suffix

### PR DESCRIPTION
**Pull request by PiwwowPants**
To avoid overwriting stable versions of the application when testing on production devices, I modified the debug build type to install separately from the release version as well as display a different icon (inverted color) and "DEBUG" at the end of its name to avoid confusion.

No other changes were made but the app name and icon in the AndroidManifest.xml file are based on items in the generated.xml file which get created when gradle builds, so testing release to the store / F-Droid should be done when possible

### CODE REVIEW

**Comment by proninyaroslav** [comment]
Quite an interesting approach, ok.

**Comment by proninyaroslav** [comment]
I think that it doesn't see path to the resources:

default

**Comment by PiwwowPants** [comment]
Can you try a clean and rebuild? I think it has to do with the order of the generated values. I only got that on my first change then switching from release to debug since it still had the original release values. 

If it's persistent for you, it can be changed just by making separate manifests for Release and Debug that define the correct paths to override the ones in Main.

**Comment by proninyaroslav** [comment]
I completely deleted and then pull repo.

**Comment by PiwwowPants** [comment]
Not sure why it is not working for you but I did it the "stock", less fancy way in this change https://github.com/proninyaroslav/libretorrent/pull/152

**Pull request merged**
