### PR TITLE
Updated icon with Material Design shadows

### PR DESCRIPTION
**Pull request by rodrigoswz**

### CODE REVIEW

**Comment by proninyaroslav** [comment]
Hello. Background of icon should have a shadow?

**Comment by rodrigoswz** [comment]
Hi, yes only the edges. It is better to see, more consistent not you think? :D Like Google Apps.

https://material.google.com/style/icons.html#icons-product-icons

**Comment by proninyaroslav** [comment]
Can you add this to the svg files (/doc/icon)?

**Comment by proninyaroslav** [comment]
I had to reverting svg, since you put in svg file png image. I meant to add a vector shadow, not png.

**Comment by rodrigoswz** [comment]
Yes, I realized, was trying fix now, I never used a svg file before. Sorry.

**Comment by proninyaroslav** [comment]
Use Inkscape for this.

**Pull request merged**
