### PR TITLE
Update AndroidManifest.xml

### PR DESCRIPTION
**Pull request by igor-dyatlov**

### CODE REVIEW

**Comment by GeoZac** [comment]
Just a useless enhancement, to properly implement you need to create a new resource with white padding.

**Comment by GeoZac** [comment]
This works best for irregular shaped icons,for instance ,Google CalenderRegular IconRound Icon 

The most appropriate implementation would be the Adaptive icons of SDK26,which uses vector drawables and supports more shapes.

**Comment by proninyaroslav** [comment]
@igor-dyatlov 

> this code helps to correctly display icons in third-party launchers, such as Lawnchair launcher

That is, on this launcher the libretorrent icon is incorrectly displayed?

**Comment by proninyaroslav** [comment]
I checked it in the Lawnchair launcher and icon is displayed correctly. I close this requester, but if someone finds out error it is, don't hesitate to do the pull requester again.

**Pull request closed without merging**
